---
- name: Requesting adguard frontend password.
  pause:
    prompt: Enter password
    echo: no
  register: adguard_frontend_pass_input

- name: Setting helper variables.
  ansible.builtin.set_fact:
    docker_file_dir: "{{ docker_working_dir }}/adguardhome"
    adguard_config_folder: "{{ docker_working_dir }}/conf"
    adguard_frontend_pass: "{{ adguard_frontend_pass_input.user_input }}"

- name: Create config directory.
  ansible.builtin.file:
    path: "{{ adguard_config_folder }}"
    state: directory
    mode: 0750

- name: Copy zigbee2mqtt config template into config directory.
  ansible.builtin.template:
    src: AdGuardHome.yaml.j2
    dest: "{{ adguard_config_folder }}/AdGuardHome.yaml"
    force: no
    mode: 0640

- name: Create adguard home container.
  community.docker.docker_container:
    name: adguard_home
    image: adguard/adguardhome:latest
    restart_policy: unless-stopped
    env:
      TZ=Europe/Berlin
    published_ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "80:80/tcp"
    volumes:
      - "{{ docker_file_dir }}/work:/opt/adguardhome/work"
      - "{{ adguard_config_folder }}:/opt/adguardhome/conf"
