---
- name: Ensure dependencies are installed (Debian).
  become: yes
  ansible.builtin.apt:
    name:
      - libffi-dev
      - libssl-dev
      - python3-dev
      - python3-pip
      - git
      - rsync
    state: present
  when: 
    - ansible_facts.os_family == "Debian"
    - "'zigbee2mqtt' in docker_services_installs or 'pigallery2' in docker_services_installs"

- name: Install Docker Compose using Pip.
  ansible.builtin.pip:
    name: docker-compose
    state: present
    executable: pip3
  when:
    - "'zigbee2mqtt' in docker_services_installs or 'pigallery2' in docker_services_installs"

- name: Ensure Docker is started.
  become: yes
  ansible.builtin.service:
    name: docker
    state: started
    enabled: yes

- name: "Ensure {{ ansible_facts['user_id'] }} user is added to the docker group."
  become: yes
  ansible.builtin.user:
    name: "{{ ansible_facts['user_id'] }}"
    groups: docker
    append: yes

# reset_connection doesn't support conditionals.
- name: Reset connection so docker group is picked up.
  meta: reset_connection

- name: Setting helper variables
  ansible.builtin.set_fact:
    docker_working_dir: "/home/{{ ansible_facts['user_id'] }}"
