---
- name: Restart docker compose
  community.docker.docker_compose:
    project_src: "{{ docker_compose_file_dir }}"
    restarted: yes
  listen: docker compose restart
  when: docker_compose_task.changed

- name: Restart docker container
  community.docker.docker_container:
    name: "{{ docker_container_name }}"
    state: started
    restart: yes
  listen: docker restart
